id: File Enrichment - Generic Test
version: -1
name: File Enrichment - Generic Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 10c4378f-44df-4293-8f72-874b0495a27a
    type: start
    task:
      id: 10c4378f-44df-4293-8f72-874b0495a27a
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
  "1":
    id: "1"
    taskid: 573632f5-8257-4ae0-88c0-7fdfb169112a
    type: regular
    task:
      id: 573632f5-8257-4ae0-88c0-7fdfb169112a
      version: -1
      name: Add File MD5 to context
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: File.MD5
      value:
        simple: 3f066dd1f1da052248aed5abc4a0c6a1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
  "2":
    id: "2"
    taskid: 8035b34b-ba2c-49f9-833b-2212997f24ed
    type: regular
    task:
      id: 8035b34b-ba2c-49f9-833b-2212997f24ed
      version: -1
      name: Add File SHA1 to context
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: File.SHA1
      value:
        simple: 795b33795f0308fc5e83abc2daff1d7129dfa400
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
  "3":
    id: "3"
    taskid: b24632ae-ecab-4d15-8d4c-be64d7ec2bdb
    type: regular
    task:
      id: b24632ae-ecab-4d15-8d4c-be64d7ec2bdb
      version: -1
      name: Add File SHA256 to context
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: File.SHA256
      value:
        simple: afd3b729cf99fb9ea441f42862a4835d1d6eeb36ee535f9b206e3a00382c972e
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
  "7":
    id: "7"
    taskid: dbe85baf-e6b6-430c-8ef9-718922014dab
    type: condition
    task:
      id: dbe85baf-e6b6-430c-8ef9-718922014dab
      version: -1
      name: Verify DBotScore context fields
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: DBotScore.Indicator
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: DBotScore.Type
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: DBotScore.Vendor
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: DBotScore.Score
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
  "8":
    id: "8"
    taskid: f083cfd3-28ab-4f13-8692-32ae498df885
    type: title
    task:
      id: f083cfd3-28ab-4f13-8692-32ae498df885
      version: -1
      name: Done
      type: title
      description: ""
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1240
        }
      }
    note: false
    timertriggers: []
  "9":
    id: "9"
    taskid: 144f05c5-0c6b-45a4-8c74-46e471288276
    type: playbook
    task:
      id: 144f05c5-0c6b-45a4-8c74-46e471288276
      version: -1
      name: File Enrichment - Generic
      playbookName: File Enrichment - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      MD5:
        complex:
          root: File
          accessor: MD5
      SHA1:
        complex:
          root: File
          accessor: SHA1
      SHA256:
        complex:
          root: File
          accessor: SHA256
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
  "10":
    id: "10"
    taskid: ce25dbaf-20e4-41df-8430-43901ebd7778
    type: regular
    task:
      id: ce25dbaf-20e4-41df-8430-43901ebd7778
      version: -1
      name: Make test fail
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      message:
        simple: Not all DBotScore context fields were created.
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 410,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1255,
        "width": 740,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
