id: e5d57a34-c821-4109-86b1-b5042c286c10
version: 2
name: test mocks playback
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: d2643672-64b9-4b49-80c9-ed22cde45b2a
    type: start
    task:
      id: d2643672-64b9-4b49-80c9-ed22cde45b2a
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: 64289c09-7c4e-434b-8844-86be7546223e
    type: regular
    task:
      id: 64289c09-7c4e-434b-8844-86be7546223e
      version: -1
      name: test-playback
      script: Mock_test_integration|||test-playback
      type: regular
      iscommand: true
      brand: Mock_test_integration
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: 9ef66642-537c-4538-8e3c-d4d83b7a88da
    type: condition
    task:
      id: 9ef66642-537c-4538-8e3c-d4d83b7a88da
      version: -1
      name: Verify Context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ${MockTest.message}
            iscontext: true
          right:
            value:
              simple: replay this
    view: |-
      {
        "position": {
          "x": 450,
          "y": 420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: dc859077-08bc-4912-8856-645032033924
    type: title
    task:
      id: dc859077-08bc-4912-8856-645032033924
      version: -1
      name: Passed
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 640
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {
      "2_3_yes": 0.54
    },
    "paper": {
      "dimensions": {
        "height": 655,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
