id: IP Enrichment - External - Generic
version: -1
name: IP Enrichment - External - Generic
fromversion: 4.1.0
description: |-
  Enrich IP using one or more integrations.

  IP enrichment includes:
  * Resolve IP to Hostname (DNS)
  * Threat information
  * Separate internal and external addresses
  * IP reputation
  * For internal addresses, get host information
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 6635b28b-bdf1-42cf-88bc-14ad75e9ebe0
    type: start
    task:
      id: 6635b28b-bdf1-42cf-88bc-14ad75e9ebe0
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "28"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 49
        }
      }
    note: false
    timertriggers: []
  "15":
    id: "15"
    taskid: c8d8906f-cbf4-4ddd-84e6-1e55570d00a0
    type: condition
    task:
      id: c8d8906f-cbf4-4ddd-84e6-1e55570d00a0
      version: -1
      name: Is there an external IP address?
      description: Checks whether the "InRange" attribute is set to "no".
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "39"
      "yes":
      - "34"
    scriptarguments:
      value:
        complex:
          root: IP
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: IP.InRange
                iscontext: true
              right:
                value:
                  simple: "no"
          accessor: Address
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: IP
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: IP.InRange
                      iscontext: true
                    right:
                      value:
                        simple: "no"
                    ignorecase: true
                accessor: Address
            iscontext: true
          ignorecase: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 590
        }
      }
    note: false
    timertriggers: []
  "19":
    id: "19"
    taskid: f4361b4a-8335-44cf-8dd4-7c2ab6fd84b7
    type: regular
    task:
      id: f4361b4a-8335-44cf-8dd4-7c2ab6fd84b7
      version: -1
      name: Check IP reputation
      description: Get the IP reputation from every integration that supports the
        `!ip` command.
      script: '|||ip'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      fullResponse: {}
      ip:
        complex:
          root: IP
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: IP.InRange
                iscontext: true
              right:
                value:
                  simple: "no"
          accessor: Address
          transformers:
          - operator: uniq
      long: {}
      retries: {}
      sampleSize: {}
      threshold: {}
      wait: {}
    reputationcalc: 2
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -40,
          "y": 1523
        }
      }
    note: false
    timertriggers: []
  "24":
    id: "24"
    taskid: 8149db7c-af8d-41e2-85ee-c9fe2efd5040
    type: title
    task:
      id: 8149db7c-af8d-41e2-85ee-c9fe2efd5040
      version: -1
      name: Done
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -400,
          "y": 2050
        }
      }
    note: false
    timertriggers: []
  "27":
    id: "27"
    taskid: 1734f24b-0b27-431e-81b6-89997f08894c
    type: title
    task:
      id: 1734f24b-0b27-431e-81b6-89997f08894c
      version: -1
      name: Enrich external IP addresses
      description: ""
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "36"
      - "40"
      - "41"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 160,
          "y": 1140
        }
      }
    note: false
    timertriggers: []
  "28":
    id: "28"
    taskid: 13e467ea-87c1-4ecc-808c-2b8e67e0f39e
    type: condition
    task:
      id: 13e467ea-87c1-4ecc-808c-2b8e67e0f39e
      version: -1
      name: Are there any IP addresses?
      description: Determine whether the playbook's input contains an IP address.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "39"
      "yes":
      - "29"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: inputs.IP
            iscontext: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
  "29":
    id: "29"
    taskid: 24cd44a3-b0ce-4c6e-8687-074e90599b22
    type: regular
    task:
      id: 24cd44a3-b0ce-4c6e-8687-074e90599b22
      version: -1
      name: Determine whether the IP address is internal or external
      description: "Checks if the IP address is in the internal IP address ranges.\nAdds
        \ \"yes\" to the \"InRange\" attribute of the IP address  if it is internal.
        \nAdds \"no\"  to the \"InRange\" attribute of the IP address  if it is external.
        \n"
      scriptName: IsIPInRanges
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      ip:
        complex:
          root: inputs.IP
          transformers:
          - operator: uniq
      ipRanges:
        complex:
          root: inputs.InternalRange
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 385
        }
      }
    note: false
    timertriggers: []
  "34":
    id: "34"
    taskid: 1bd57324-7ece-47a0-8e22-ebd341ecd0a4
    type: condition
    task:
      id: 1bd57324-7ece-47a0-8e22-ebd341ecd0a4
      version: -1
      name: Resolve the IP address?
      description: Checks whether the ResolveIP parameter is set to "True".
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "27"
      "yes":
      - "35"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: inputs.ResolveIP
            iscontext: true
          right:
            value:
              simple: "True"
          ignorecase: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 800
        }
      }
    note: false
    timertriggers: []
  "35":
    id: "35"
    taskid: 9a9092a5-a173-4c8d-8a0c-f63960c42451
    type: regular
    task:
      id: 9a9092a5-a173-4c8d-8a0c-f63960c42451
      version: -1
      name: IP to Hostname (DNS)
      description: Convert the IP address to a hostname using DNS query.
      scriptName: IPToHost
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "27"
    scriptarguments:
      ip:
        complex:
          root: IP
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: IP.InRange
                iscontext: true
              right:
                value:
                  simple: "no"
          - - operator: containsGeneral
              left:
                value:
                  simple: IP.Address
                iscontext: true
              right:
                value:
                  simple: inputs.IP
                iscontext: true
          accessor: Address
          transformers:
          - operator: uniq
    reputationcalc: 2
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 520,
          "y": 970
        }
      }
    note: false
    timertriggers: []
  "36":
    id: "36"
    taskid: 22f7b81d-ea1a-44b3-8b73-c628afaf5cfc
    type: title
    task:
      id: 22f7b81d-ea1a-44b3-8b73-c628afaf5cfc
      version: -1
      name: Enrich Using VirusTotal Private API
      description: ""
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "37"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 442,
          "y": 1345
        }
      }
    note: false
    timertriggers: []
  "37":
    id: "37"
    taskid: 886830c0-ea16-4a06-8170-41c05b587259
    type: condition
    task:
      id: 886830c0-ea16-4a06-8170-41c05b587259
      version: -1
      name: Is Virus Total Private API enabled?
      description: Checks if there is an active instance of the Virus Total Private
        API enabled.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "38"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: VirusTotal - Private API
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                accessor: brand
            iscontext: true
          ignorecase: true
    view: |-
      {
        "position": {
          "x": 442,
          "y": 1523
        }
      }
    note: false
    timertriggers: []
  "38":
    id: "38"
    taskid: b16c1c31-82c1-48ce-8607-df2f08b47a20
    type: regular
    task:
      id: b16c1c31-82c1-48ce-8607-df2f08b47a20
      version: -1
      name: Get IP report from Virus Total Private API
      description: |
        Retrieves a report for a given IP.
      script: VirusTotal - Private API|||vt-private-get-ip-report
      type: regular
      iscommand: true
      brand: VirusTotal - Private API
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      fullResponse: {}
      ip:
        complex:
          root: IP
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: IP.InRange
                iscontext: true
              right:
                value:
                  simple: "no"
          accessor: Address
          transformers:
          - operator: uniq
      threshold: {}
    reputationcalc: 2
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 442,
          "y": 1720
        }
      }
    note: false
    timertriggers: []
  "39":
    id: "39"
    taskid: 67d938bf-2bd3-4dfd-885f-8dd190cd0b93
    type: title
    task:
      id: 67d938bf-2bd3-4dfd-885f-8dd190cd0b93
      version: -1
      name: No External IP Address
      description: ""
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "24"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -560,
          "y": 950
        }
      }
    note: false
    timertriggers: []
  "40":
    id: "40"
    taskid: 325d3bf7-4191-40c0-818c-b325ea06b15a
    type: condition
    task:
      id: 325d3bf7-4191-40c0-818c-b325ea06b15a
      version: -1
      name: Check IP reputation?
      description: Determines whether reputation should be checked from IP Addresses.
        This is flag is taken from the Entity Enrichment - Generic playbook.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "19"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: inputs.GetReputation
            iscontext: true
          right:
            value:
              simple: "True"
          ignorecase: true
    view: |-
      {
        "position": {
          "x": -40,
          "y": 1330
        }
      }
    note: false
    timertriggers: []
  "41":
    id: "41"
    taskid: 8828c9f9-9144-42ab-8c98-7479e8f19a04
    type: title
    task:
      id: 8828c9f9-9144-42ab-8c98-7479e8f19a04
      version: -1
      name: Enrich Using Threat Crowd
      description: ""
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "42"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 920,
          "y": 1345
        }
      }
    note: false
    timertriggers: []
  "42":
    id: "42"
    taskid: 02350f3e-c374-459c-855a-9e2453ec8697
    type: condition
    task:
      id: 02350f3e-c374-459c-855a-9e2453ec8697
      version: -1
      name: Is Threat Crowd enabled?
      description: Checks if there is an active instance of Threat Crowd enabled.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "43"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: Threat Crowd
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                accessor: brand
            iscontext: true
          ignorecase: true
    view: |-
      {
        "position": {
          "x": 920,
          "y": 1523
        }
      }
    note: false
    timertriggers: []
  "43":
    id: "43"
    taskid: f03d81e7-d7ea-40a3-86bb-94c90e7694f2
    type: regular
    task:
      id: f03d81e7-d7ea-40a3-86bb-94c90e7694f2
      version: -1
      name: Get IP report from Threat Crowd
      description: |
        Retrieves a report for a given IP.
      script: '|||threat-crowd-ip'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      ip:
        complex:
          root: IP
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: IP.InRange
                iscontext: true
              right:
                value:
                  simple: "no"
          accessor: Address
          transformers:
          - operator: uniq
    reputationcalc: 2
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 920,
          "y": 1710
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {
      "15_34_yes": 0.58,
      "15_39_#default#": 0.51,
      "28_29_yes": 0.68,
      "28_39_#default#": 0.35,
      "34_27_#default#": 0.49,
      "34_35_yes": 0.53,
      "37_24_#default#": 0.42,
      "37_38_yes": 0.52,
      "40_19_yes": 0.63,
      "42_24_#default#": 0.28
    },
    "paper": {
      "dimensions": {
        "height": 2066,
        "width": 1860,
        "x": -560,
        "y": 49
      }
    }
  }
inputs:
- key: IP
  value:
    complex:
      root: IP
      accessor: Address
  required: false
  description: The IP address to enrich.
- key: InternalRange
  value: {}
  required: false
  description: |-
    The internal range to check against the IP address.
    The default range is taken from the IPv4 protocol.
- key: ResolveIP
  value:
    complex:
      root: inputs.ResolveIP
  required: true
  description: Convert the IP address to a hostname using a DNS query (True/ False).
- key: GetReputation
  value:
    complex:
      root: inputs.GetReputation
  required: false
  description: |-
    Determines whether to get reputation for the supported entities, using "!command" (such as "!ip"). Supported entities:
    - IP
    - File
    - URL
    - Domain
outputs:
- contextPath: IP
  description: The IP objects
  type: unknown
- contextPath: DBotScore
  description: Indicator, Score, Type, Vendor
  type: unknown
- contextPath: Endpoint
  description: The Endpoint's object
  type: unknown
- contextPath: Endpoint.Hostname
  description: The hostname to enrich
  type: string
- contextPath: Endpoint.OS
  description: Endpoint OS
  type: string
- contextPath: Endpoint.IP
  description: List of endpoint IP addresses
- contextPath: Endpoint.MAC
  description: List of endpoint MAC addresses
- contextPath: Endpoint.Domain
  description: Endpoint domain name
  type: string
releaseNotes: "A new generic playbook for external IP enrichment (now as a separate playbook)"
tests:
  - IP Enrichment - Generic - NonReputation Test